Repository thoth-station/prescriptions-refresh-job, pull requests merged in 2021-11, with the labels that each got.

#40 Create boot for gating CVE issues in the runtime environment
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/M, approved

#49 Keep datetime in the Quay security timestamp boot in metadata
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/XS, approved

#50 Sort response from Quay API to keep prescription changes consistent
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/XS, approved

#53 use https based url in the pre-commit
  .pre-commit-config.yaml
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/XS, approved

#48 Compute alternatives to container images with vulnerabilities
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/L, approved

#56 Use double quotes to make pre-commit happy
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/XS, approved

#58 Add also tag part to prescription name in Quay security
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/XS, lgtm, approved

#59 Do not fail if Quay returns status code other than 200
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/S, approved

#60 Add Pep to OWNERS file
  OWNERS
Labels: size/XS, approved
