Repository thoth-station/prescriptions-refresh-job, pull requests merged in 2021-12, with the labels that each got.

#66 Add a general method to Prescriptions to generate prescription names
  thoth/prescriptions_refresh/handlers/cve_warning.py
  thoth/prescriptions_refresh/handlers/gh_archived.py
  thoth/prescriptions_refresh/handlers/gh_contributors.py
  thoth/prescriptions_refresh/handlers/gh_forked.py
  thoth/prescriptions_refresh/handlers/gh_link.py
  thoth/prescriptions_refresh/handlers/gh_popularity.py
  thoth/prescriptions_refresh/handlers/gh_release_notes.py
  thoth/prescriptions_refresh/handlers/gh_updated.py
  thoth/prescriptions_refresh/handlers/quay_security.py
  thoth/prescriptions_refresh/handlers/scorecards.py
  thoth/prescriptions_refresh/handlers/thoth_community/handler.py
  thoth/prescriptions_refresh/prescriptions.py
Labels: size/L, approved

#69 Fix obtaining prescription name
  thoth/prescriptions_refresh/handlers/gh_link.py
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/XS, approved

#71 Add Maya to OWNERS
  OWNERS
Labels: size/XS, approved

#65 Add a handler for package downloads information
  thoth/prescriptions_refresh/cli.py
  thoth/prescriptions_refresh/handlers/pypi_downloads.py
Labels: size/L, approved

#70 Minor fix in typing
  thoth/prescriptions_refresh/handlers/thoth_community/handler.py
Labels: size/XS, approved

#77 Fix errors in pre-commit for pypi_downloads.py
  thoth/prescriptions_refresh/handlers/pypi_downloads.py
Labels: size/M, approved

#79 Add pypi_downloads to __init__.py
  thoth/prescriptions_refresh/handlers/__init__.py
Labels: size/XS, approved

#68 Warn if a package has no recent releases
  Pipfile
  Pipfile.lock
  thoth/prescriptions_refresh/cli.py
  thoth/prescriptions_refresh/handlers/__init__.py
  thoth/prescriptions_refresh/handlers/pypi_release.py
Labels: size/L, approved

#74 Parametrize message with constant supplied
  thoth/prescriptions_refresh/handlers/pypi_downloads.py
Labels: size/S, approved

#80 Introduce handler for computing PyPI artifact size
  thoth/prescriptions_refresh/cli.py
  thoth/prescriptions_refresh/handlers/__init__.py
  thoth/prescriptions_refresh/handlers/pypi_artifact_size.py
Labels: size/L, approved

#82 Artifact size is computed per package version
  thoth/prescriptions_refresh/handlers/pypi_artifact_size.py
Labels: size/XS, approved

#83 Be consistent with quoting names and versions
  thoth/prescriptions_refresh/handlers/pypi_maintainers.py
Labels: size/XS, approved

#85 Fix version range specifier for matching Python versions
  thoth/prescriptions_refresh/handlers/pypi_artifact_size.py
Labels: size/XS, approved

#86 Do not quote index_url as pre-commit complains about it
  thoth/prescriptions_refresh/handlers/pypi_maintainers.py
Labels: size/XS, approved

#88 Avoid empty line in prescriptions computing container image alternatives
  thoth/prescriptions_refresh/handlers/quay_security.py
Labels: size/XS, approved

#84 Propagate information about container image size from Quay
  thoth/prescriptions_refresh/cli.py
  thoth/prescriptions_refresh/handlers/__init__.py
  thoth/prescriptions_refresh/handlers/pypi_artifact_size.py
  thoth/prescriptions_refresh/handlers/quay/__init__.py
  thoth/prescriptions_refresh/handlers/quay/common.py
  thoth/prescriptions_refresh/handlers/quay/image_size.py
  thoth/prescriptions_refresh/handlers/quay/security.py
  thoth/prescriptions_refresh/prescriptions.py
Labels: size/L, approved

#90 Put character between version numbers in pipeline unit names to avoid conflicts
  thoth/prescriptions_refresh/prescriptions.py
Labels: size/XS, approved

#89 Apply solver rules to package versions used to generate prescriptions
  Pipfile
  Pipfile.lock
  thoth/prescriptions_refresh/handlers/pypi_artifact_size.py
Labels: size/L, approved

#98 Describe environment variables used to run the job
  .env.template
  README.rst
Labels: size/M, approved

#100 Document how to run the job locally
  README.rst
Labels: size/M, approved

#101 Make justifications for vulnerabilities short
  thoth/prescriptions_refresh/handlers/quay/security.py
Labels: size/S, approved

#106 Add missing Thoth GitHub templates
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_info.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
Labels: size/M, approved

#107 Fix README formatting
  README.rst
Labels: size/XS, approved

#97 Add handler for thoth image analysis command
  .env.template
  README.rst
  thoth/prescriptions_refresh/cli.py
  thoth/prescriptions_refresh/handlers/__init__.py
  thoth/prescriptions_refresh/handlers/image_analysis.py
  thoth/prescriptions_refresh/handlers/quay/common.py
  thoth/prescriptions_refresh/handlers/quay/image_size.py
  thoth/prescriptions_refresh/handlers/quay/security.py
  thoth/prescriptions_refresh/prescriptions.py
Labels: size/L, approved

#108 Missed commit suggestion
  thoth/prescriptions_refresh/handlers/image_analysis.py
Labels: size/XS, approved

#110 Fix api calls and add PROTOCOL_SCHEMA env variable
  .env.template
  README.rst
  thoth/prescriptions_refresh/handlers/image_analysis.py
Labels: size/S, approved

#112 Scheme protocol is only for user-API
  README.rst
Labels: size/XS, approved
