Repository thoth-station/prescriptions-refresh-job, pull requests merged in 2022-07, with the labels that each got.

#174 Add labels to BigQuery queries
  thoth/prescriptions_refresh/handlers/pypi_downloads.py
  thoth/prescriptions_refresh/handlers/scorecards.py
Labels: size/S, approved

#178 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: size/XS, approved, ok-to-test

#177 Add tags to scorecards prescriptions
  thoth/prescriptions_refresh/handlers/scorecards.py
Labels: size/M, lgtm, approved

#183 :recycle: HouseKeeping: Updated pre-commit and OWNERS
  .pre-commit-config.yaml
  .prow.yaml
  OWNERS
  OWNERS_ALIASES
Labels: size/S
